<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/differential/field/selector/base');
phutil_require_module('phabricator', 'applications/differential/field/selector/default');
phutil_require_module('phabricator', 'applications/differential/field/specification/base');


phutil_require_source('CoverageFieldSpecification.php');
phutil_require_source('DisqusDifferentialFieldSpecification.php');
