<?php
/**
 * This file is automatically generated. Lint this module to rebuild it.
 * @generated
 */



phutil_require_module('phabricator', 'applications/maniphest/constants/transactiontype');
phutil_require_module('phabricator', 'applications/project/storage/affiliation');
phutil_require_module('phabricator', 'applications/project/storage/project');
phutil_require_module('phabricator', 'infrastructure/events/constant/type');

phutil_require_module('phutil', 'events/listener');
phutil_require_module('phutil', 'utils');


phutil_require_source('DesignDecisionEventListener.php');
phutil_require_source('ProjectAssignmentEventListener.php');
