<?php

/**
 * This file is automatically generated. Use 'arc liberate' to rebuild it.
 *
 * @generated
 * @phutil-library-version 2
 */
phutil_register_library_map(array(
  '__library_version__' => 2,
  'class' => array(
    'ArcanistCodeLinter' => 'lint/linter/ArcanistEncodingLinter.php',
    'ArcanistIsortLinter' => 'lint/linter/ArcanistIsortLinter.php',
    'ArcanistESLintLinter' => 'lint/linter/ArcanistESLintLinter.php',
    'CoverageFieldSpecification' => 'diff/CoverageFieldSpecification.php',
    'DisqusConfiguration' => 'configuration/DisqusConfiguration.php',
    'DisqusDifferentialFieldSelector' => 'diff/DisqusDifferentialFieldSpecification.php',
    'DisqusLintEngine' => 'lint/engine/DisqusLintEngine.php',
    'DisqusUnitTestEngine' => 'unittest/DisqusUnitTestEngine.php',
    'DjangoUnitTestEngine' => 'unittest/DjangoUnitTestEngine.php',
    'GenericXUnitTestEngine' => 'unittest/GenericXUnitTestEngine.php',
    'JenkinsDiffEventListener' => 'event/JenkinsDiffEventListener.php',
    'PhabricatorBotDocHandler' => 'bot/handler/PhabricatorBotDocHandler.php',
    'PyTestUnitTestEngine' => 'unittest/PyTestUnitTestEngine.php',
    'PythonBaseUnitTestEngine' => 'unittest/PythonBaseUnitTestEngine.php',
    'SentryLogger' => 'sentrylogger/SentryLogger.php',
    'SetupPyUnitTestEngine' => 'unittest/SetupPyUnitTestEngine.php',
  ),
  'function' => array(
    'microtime_float' => 'unittest/PythonBaseUnitTestEngine.php',
  ),
  'xmap' => array(
    'ArcanistCodeLinter' => 'ArcanistLinter',
    'ArcanistIsortLinter' => 'ArcanistExternalLinter',
    'ArcanistESLintLinter' => 'ArcanistExternalLinter',
    'CoverageFieldSpecification' => 'DifferentialFieldSpecification',
    'DisqusConfiguration' => 'ArcanistConfiguration',
    'DisqusDifferentialFieldSelector' => 'DifferentialFieldSelector',
    'DisqusLintEngine' => 'ArcanistLintEngine',
    'DisqusUnitTestEngine' => 'ArcanistUnitTestEngine',
    'DjangoUnitTestEngine' => 'PythonBaseUnitTestEngine',
    'GenericXUnitTestEngine' => 'ArcanistUnitTestEngine',
    'JenkinsDiffEventListener' => 'PhutilEventListener',
    'PhabricatorBotDocHandler' => 'PhabricatorBotHandler',
    'PyTestUnitTestEngine' => 'PythonBaseUnitTestEngine',
    'PythonBaseUnitTestEngine' => 'ArcanistUnitTestEngine',
    'SetupPyUnitTestEngine' => 'PythonBaseUnitTestEngine',
  ),
));
