<?php

/**
 * This file is automatically generated. Use 'phutil_mapper.php' to rebuild it.
 * @generated
 */

phutil_register_library_map(array(
  'class' =>
  array(
    'CoverageFieldSpecification' => 'diff',
    'DisqusConfiguration' => 'configuration',
    'DisqusDifferentialFieldSelector' => 'diff',
    'DisqusLintEngine' => 'lint',
    'DisqusPEP8Linter' => 'lint/linters/pep8',
    'DisqusUnitTestEngine' => 'unittest',
    'ProjectAssignmentEventListener' => 'event',
    'ProjectAssignmentEventListenerTestCase' => 'event/__tests__',
  ),
  'function' =>
  array(
  ),
  'requires_class' =>
  array(
    'CoverageFieldSpecification' => 'DifferentialFieldSpecification',
    'DisqusConfiguration' => 'ArcanistConfiguration',
    'DisqusDifferentialFieldSelector' => 'DifferentialFieldSelector',
    'DisqusLintEngine' => 'ArcanistLintEngine',
    'DisqusPEP8Linter' => 'ArcanistPEP8Linter',
    'DisqusUnitTestEngine' => 'ArcanistBaseUnitTestEngine',
    'ProjectAssignmentEventListener' => 'PhutilEventListener',
    'ProjectAssignmentEventListenerTestCase' => 'PhabricatorTestCase',
  ),
  'requires_interface' =>
  array(
  ),
));
