<?php

/**
 * This file is automatically generated. Use 'phutil_mapper.php' to rebuild it.
 * @generated
 */

phutil_register_library_map(array(
  'class' =>
  array(
    'CoverageFieldSpecification' => 'diff',
    'DesignDecisionEventListener' => 'event',
    'DisqusConfiguration' => 'configuration',
    'DisqusCreateConfigWorkflow' => 'workflow/create-config',
    'DisqusDifferentialFieldSelector' => 'diff',
    'DisqusGitConfigureTemplateWorkflow' => 'workflow/git-configure-template',
    'DisqusUnitTestEngine' => 'unittest',
    'MockManiphestTask' => 'event/__tests__',
    'MockedProjectAssignmentEventListener' => 'event/__tests__',
    'ProjectAssignmentEventListener' => 'event',
    'ProjectAssignmentEventListenerTestCase' => 'event/__tests__',
  ),
  'function' =>
  array(
  ),
  'requires_class' =>
  array(
    'CoverageFieldSpecification' => 'DifferentialFieldSpecification',
    'DesignDecisionEventListener' => 'PhutilEventListener',
    'DisqusConfiguration' => 'ArcanistConfiguration',
    'DisqusCreateConfigWorkflow' => 'ArcanistBaseWorkflow',
    'DisqusDifferentialFieldSelector' => 'DifferentialFieldSelector',
    'DisqusGitConfigureTemplateWorkflow' => 'ArcanistBaseWorkflow',
    'DisqusUnitTestEngine' => 'ArcanistBaseUnitTestEngine',
    'MockManiphestTask' => 'ManiphestTask',
    'MockedProjectAssignmentEventListener' => 'ProjectAssignmentEventListener',
    'ProjectAssignmentEventListener' => 'PhutilEventListener',
    'ProjectAssignmentEventListenerTestCase' => 'PhabricatorTestCase',
  ),
  'requires_interface' =>
  array(
  ),
));
